Attempt to fix ibis import error:
AttributeError: partially initialized module 'ibis.expr.types' has no attribute 'UnknownScalar' (most likely due to a circular import)