fix: Fix materialization details error handling (#282)
* fix: Fix materialization details error handling

* pixi update

* Somehow sa.select("*") can create a race condition with prefect backend. Thus changed to sa.select(sa.text("*")).

This error vanished always on second run:

Split tests into 2 parallelization groups: dask_engine, prefect_engine
..............F.................................................ssssssss [ 52%]
s..................................................sssssssss....         [100%]
=================================== FAILURES ===================================
______________ test_materialize_view_union[prefect_engine-False] _______________

instance = '*'

    @inspection._inspects(object)
    def _inspect_mapped_object(instance: _T) -> Optional[InstanceState[_T]]:
        try:
>           return instance_state(instance)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
E           AttributeError: 'str' object has no attribute '_sa_instance_state'

.pixi/envs/py311all/lib/python3.11/site-packages/sqlalchemy/orm/base.py:430: AttributeError

* Prevent version conflict for ibm_db=3.2.7

* Convert auto_table error to warning in pipedag tests.

It is a bit lame to catch one specific type but this type is helpful in the general auto_table arguments and this is hard to make dependent on pydiverse.transform being installed.

* Convert auto_table error to warning in pipedag tests.

Prepare release 0.11.0

---------

Co-authored-by: windiana42 <windiana@users.sf.net>