Support duckdb 1.4.1 (1.4.0 had problem with sqlalchemy) (#290)
* Support duckdb 1.4.1

* Avoid strange error message about sync_views table missing.

However, this is just a half baked fix. In fact, a technical protection is needed to avoid reuse of same pipedag_metadata schema as external metadata store for ParquetTableStore and as native metadata.

https://github.com/pydiverse/pydiverse.pipedag/issues/289

* Fix log level in conftest.py

* Update examples in documentation to use new 0.12.0 version.

* Pin duckdb<1.4 for ibis tests.

# E   AttributeError: module 'duckdb' has no attribute 'functional'
#
# ../.pixi/envs/py313all/lib/python3.13/site-packages/ibis/backends/duckdb/__init__.py:52: AttributeError

* Make table hooks work even without ConfigContext (see example_mssql/download_parquet_files.py)

* Fix github action release check.

* Prepare release 0.12.1