polars 1.33.1 does not support UPath (S3) in df.write_parquet
TypeError: `path` argument has invalid type 'upath.implementations.cloud.S3Path', and cannot be turned into a sink target